In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.9.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

In [ ]:
!pip install --upgrade transformers tensorflow

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.9.0)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.21.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (7.35.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.12.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [ ]:
df_train = pd.read_csv('/content/train_cleaned_checkpoint.csv')
df_test = pd.read_csv('/content/test_cleaned_checkpoint.csv')
df_valid = pd.read_csv('/content/valid_cleaned_checkpoint.csv')

# **Label Encoding**

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# fit_transform
y_train = label_encoder.fit_transform(df_train['label'])

# transform
y_valid = label_encoder.transform(df_valid['label'])
y_test  = label_encoder.transform(df_test['label'])

# Class Mapping
class_mapping = dict(zip(label_encoder.classes_, range(len(label_encoder.classes_))))
print("Emotion Class Mapping:", class_mapping)

Emotion Class Mapping: {'anger': 0, 'fear': 1, 'happy': 2, 'love': 3, 'sadness': 4}

# **Training Model (IndoBERT & IndoBERTweet)**

In [ ]:
import torch
from torch.utils.data import Dataset

from transformers import AutoTokenizer
from transformers import Trainer, TrainingArguments, EarlyStoppingCallback
from sklearn.metrics import classification_report

In [ ]:
# Format PyTorch Dataset
class EmotDataset(Dataset):
    def __init__(self, encodings_ids, encodings_masks, labels):
        self.ids = encodings_ids
        self.masks = encodings_masks
        self.labels = labels

    def __getitem__(self, idx):
        return {
            # Memastikan tipe data long (integer) untuk PyTorch
            'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
            'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
            'labels': torch.tensor(self.labels[idx], dtype=torch.long)
        }

    def __len__(self):
        return len(self.labels)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

## **A. IndoBERT**

### **1) Tokenization**

In [ ]:
from transformers import AutoTokenizer

model_checkpoint = "indolem/indobert-base-uncased"
bert_tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

# Clean tag [username] & [url]
def clean_bert(text):
    text = str(text).lower()
    text = re.sub(r'\[username\]|\[url\]', '', text)
    return text.strip()

text_train_bert = df_train['tweet'].apply(clean_bert).tolist()
text_valid_bert = df_valid['tweet'].apply(clean_bert).tolist()
text_test_bert  = df_test['tweet'].apply(clean_bert).tolist()

def prepare_bert_input(texts_list, max_len=43):
    encoded = bert_tokenizer(
        texts_list,
        add_special_tokens=True,
        max_length=max_len,
        padding='max_length',
        truncation=True,
        return_attention_mask=True,
        return_tensors='pt'
    )
    return encoded['input_ids'], encoded['attention_mask']

# Tokenization
X_train_bert_ids, X_train_bert_mask = prepare_bert_input(text_train_bert)
X_valid_bert_ids, X_valid_bert_mask = prepare_bert_input(text_valid_bert)
X_test_bert_ids, X_test_bert_mask   = prepare_bert_input(text_test_bert)

train_dataset_bert = EmotDataset(X_train_bert_ids, X_train_bert_mask, y_train)
valid_dataset_bert = EmotDataset(X_valid_bert_ids, X_valid_bert_mask, y_valid)
test_dataset_bert  = EmotDataset(X_test_bert_ids,  X_test_bert_mask,  y_test)

print(f"X_train_bert_ids Dimension: {X_train_bert_ids.shape}")

X_train_bert_ids Dimension: torch.Size([3521, 43])

### **2) Custom Head**

In [ ]:
import torch.nn as nn
from transformers import AutoModel

class IndoBERTBaseCustom(nn.Module):
    def __init__(self, num_labels, class_weights=None):
        super(IndoBERTBaseCustom, self).__init__()
        self.num_labels = num_labels
        self.class_weights = class_weights

        self.bert = AutoModel.from_pretrained("indolem/indobert-base-uncased")

        # Arsitektur Klasifikasi Custom (Shaw et al.)
        self.dense1 = nn.Linear(self.bert.config.hidden_size, 64)
        self.dropout = nn.Dropout(0.05)
        self.dense2 = nn.Linear(64, 16)
        self.classifier = nn.Linear(16, num_labels)

    def forward(self, input_ids, attention_mask, labels=None, **kwargs):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)

        # GLOBAL AVERAGE POOLING
        mask_expanded = attention_mask.unsqueeze(-1).expand(outputs.last_hidden_state.size()).float()
        sum_embeddings = torch.sum(outputs.last_hidden_state * mask_expanded, 1)
        sum_mask = torch.clamp(mask_expanded.sum(1), min=1e-9)
        pooled_output = sum_embeddings / sum_mask

        # CUSTOM CLASSIFICATION HEAD
        x = self.dense1(pooled_output)
        x = torch.relu(x)
        x = self.dropout(x)
        x = self.dense2(x)
        x = torch.relu(x)
        logits = self.classifier(x)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss(weight=self.class_weights)
            loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
            return {"loss": loss, "logits": logits}

        return {"logits": logits}

model_bert_custom = IndoBERTBaseCustom(
    num_labels=len(class_mapping)
).to(device)

pytorch_model.bin:   0%|          | 0.00/445M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: indolem/indobert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

### **3) Training**

In [ ]:
# Hyperparameter (Shaw et al.)
training_args = TrainingArguments(
    output_dir='./indobert_base_results',
    num_train_epochs=25,
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    learning_rate=3e-5,
    weight_decay=0.005,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
)

trainer = Trainer(
    model=model_bert_custom,
    args=training_args,
    train_dataset=train_dataset_bert,
    eval_dataset=valid_dataset_bert,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=5)]
)

trainer.train()

print("\n[Evaluation IndoBERT on TEST Data]")
predictions = trainer.predict(test_dataset_bert)
y_pred_bert = np.argmax(predictions.predictions, axis=1)

print(classification_report(y_test, y_pred_bert, target_names=label_encoder.classes_))

--- Memulai Proses Fine-Tuning IndoBERT Base (Custom Head) ---

/tmp/ipykernel_3747/3758758826.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),

/tmp/ipykernel_3747/3758758826.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),

[Evaluasi IndoBERT Base (Custom Head) pada Data TEST]

/tmp/ipykernel_3747/3758758826.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_3747/3758758826.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),

              precision    recall  f1-score   support

       anger       0.74      0.75      0.75       110
        fear       0.89      0.65      0.75        65
       happy       0.68      0.70      0.69       101
        love       0.68      0.80      0.73        64
     sadness       0.59      0.60      0.59       100

    accuracy                           0.70       440
   macro avg       0.72      0.70      0.70       440
weighted avg       0.71      0.70      0.70       440

In [ ]:
y_pred_bert = np.array(y_pred_bert)
np.save('y_pred_bert.npy', y_pred_bert)

## **B. IndoBERTweet (Shaw dkk.)**

### **1) Tokenization**

In [ ]:
model_checkpoint_tw = "indolem/indobertweet-base-uncased"
tokenizer_tw = AutoTokenizer.from_pretrained(model_checkpoint_tw)

def prep_indobertweet(text):
    text = str(text).lower()
    # IndoBERTweet Preprocessing: @USER, HTTPURL
    text = re.sub(r'\[username\]', '@USER', text)
    text = re.sub(r'\[url\]', 'HTTPURL', text)
    return text.strip()

X_train_tw_tweet = df_train['tweet'].apply(prep_indobertweet).tolist()
X_valid_tw_tweet = df_valid['tweet'].apply(prep_indobertweet).tolist()
X_test_tw_tweet  = df_test['tweet'].apply(prep_indobertweet).tolist()

def encode_tweet(texts, max_len=43):
    encoded = tokenizer_tw(
        texts,
        add_special_tokens=True,
        max_length=max_len,
        padding='max_length',
        truncation=True,
        return_tensors='pt'
    )
    return encoded['input_ids'], encoded['attention_mask']

train_ids_tw, train_mask_tw = encode_tweet(X_train_tw_tweet)
valid_ids_tw, valid_mask_tw = encode_tweet(X_valid_tw_tweet)
test_ids_tw, test_mask_tw   = encode_tweet(X_test_tw_tweet)

train_dataset_tw = EmotDataset(train_ids_tw, train_mask_tw, y_train)
valid_dataset_tw = EmotDataset(valid_ids_tw, valid_mask_tw, y_valid)
test_dataset_tw  = EmotDataset(test_ids_tw, test_mask_tw, y_test)

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

### **2) Custom Head**

In [ ]:
import torch.nn as nn
from transformers import AutoModel

class IndoBERTweetCustom(nn.Module):
    def __init__(self, num_labels):
        super(IndoBERTweetCustom, self).__init__()
        self.num_labels = num_labels
        self.bert = AutoModel.from_pretrained("indolem/indobertweet-base-uncased")

        # (Shaw et al.)
        self.dense1 = nn.Linear(self.bert.config.hidden_size, 64)
        self.dropout = nn.Dropout(0.05)
        self.dense2 = nn.Linear(64, 16)
        self.classifier = nn.Linear(16, num_labels)

    def forward(self, input_ids, attention_mask, labels=None, **kwargs):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)

        # GLOBAL AVERAGE POOLING
        mask_expanded = attention_mask.unsqueeze(-1).expand(outputs.last_hidden_state.size()).float()
        sum_embeddings = torch.sum(outputs.last_hidden_state * mask_expanded, 1)
        sum_mask = torch.clamp(mask_expanded.sum(1), min=1e-9)
        pooled_output = sum_embeddings / sum_mask

        # CUSTOM CLASSIFICATION HEAD
        x = self.dense1(pooled_output)
        x = torch.relu(x)
        x = self.dropout(x)
        x = self.dense2(x)
        x = torch.relu(x)
        logits = self.classifier(x)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
            return {"loss": loss, "logits": logits}

        return {"logits": logits}

model_tweet = IndoBERTweetCustom(
    num_labels=len(class_mapping),
).to(device)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: indolem/indobertweet-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

### **3) Training**

In [ ]:
# IndoBERTweet Parameter (Shaw et al.)
training_args_tw = TrainingArguments(
    output_dir='./indobertweet_results',
    num_train_epochs=25,
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    learning_rate=3e-5,
    weight_decay=0.005,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss"
)

trainer_tw = Trainer(
    model=model_tweet,
    args=training_args_tw,
    train_dataset=train_dataset_tw,
    eval_dataset=valid_dataset_tw,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=5)]
)

trainer_tw.train()

print("\n[Evaluation IndoBERTweet on TEST Data]")
predictions_tw = trainer_tw.predict(test_dataset_tw)
y_pred_tweet = np.argmax(predictions_tw.predictions, axis=1)
print(classification_report(y_test, y_pred_tweet, target_names=label_encoder.classes_))

/tmp/ipykernel_527/376574302.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),

/tmp/ipykernel_527/376574302.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),

[Evaluation IndoBERTweet on TEST Data]

/tmp/ipykernel_527/376574302.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(self.ids[idx], dtype=torch.long),
/tmp/ipykernel_527/376574302.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(self.masks[idx], dtype=torch.long),

              precision    recall  f1-score   support

       anger       0.82      0.79      0.81       110
        fear       0.75      0.82      0.78        65
       happy       0.79      0.69      0.74       101
        love       0.74      0.86      0.80        64
     sadness       0.68      0.68      0.68       100

    accuracy                           0.76       440
   macro avg       0.76      0.77      0.76       440
weighted avg       0.76      0.76      0.76       440

### **4) Save Model**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
model_final_path_drive = "/content/drive/MyDrive/indobertweet-emotion-v1"

trainer_tw.save_model(model_final_path_drive)
tokenizer_tw.save_pretrained(model_final_path_drive)

('/content/drive/MyDrive/indobertweet-emotion-v1/tokenizer_config.json',
 '/content/drive/MyDrive/indobertweet-emotion-v1/tokenizer.json')

### **5) Load Model to Save y_pred_tweet**

In [ ]:
from safetensors.torch import load_file

model_tw = IndoBERTweetCustom(
    num_labels=len(class_mapping),
)

model_path = "/content/drive/MyDrive/indobertweet-emotion-v1/model.safetensors"
weight = load_file(model_path)
model_tw.load_state_dict(weight)
model_tw.to(device)
model_tw.eval()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: indolem/indobertweet-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

IndoBERTweetCustom(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(31923, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dense1): Linear(in_features=768, out_features=64, bias=True)
  (dropout): Dropout(p=0.05, inplace=False)
  (dense2): Linear(in_features=64, out_features=16, bias=True)
  (classifier): Linear(in_features=16, out_features=5, bias=True)
)

In [ ]:
y_pred_tweet = np.array(y_pred_tweet)
np.save('y_pred_tweet.npy', y_pred_tweet)

In [ ]:
y_test = np.array(y_test)
np.save('y_test.npy', y_test)